version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo pip install tensorflow==1.12.0 tensorflow-probability==0.5.0-rc1
      - run: sudo pip install -r requirements.txt
      - run: ./test.sh
